apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    networking.gke.io/managed-certificates: frontend-cert
    # Serve index.html for all paths
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: 34.54.116.200.nip.io
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: user-frontend-service
                port:
                  number: 80
